### ISSUE TITLE
Version constraint "*" no longer matches prerelease versions, as of semver v4.3.6

### ISSUE THREAD

**Issue by benjamn** [npm/read-installed#40]
When there is no `package.json` file present (for example, in the parent directory of the top-level `node_modules` directory), [this code](https://github.com/npm/read-installed/blob/ab4a5f12603111847bbb2cc666e51c056964c58a/read-installed.js#L193) reads dependencies from the `node_modules` directory and attempts to use the catch-all version constraint, `*`.

Unfortunately, `*` no longer matches prerelease versions, after [this commit](https://github.com/npm/node-semver/commit/93a870665bba0f4be5c4edc19d6f94ff39ad60e8) in v4.3.6 of the `semver` package, which is what `npm` uses.

This effectively means that prerelease packages installed in top-level `node_modules` directories will be considered invalid by commands like `npm ls`.

I think the simplest way to fix this would be to make [this condition](https://github.com/npm/read-installed/blob/ab4a5f12603111847bbb2cc666e51c056964c58a/read-installed.js#L203-L205) fail when `reqver === "*"` (or, better, some sentinel value that cannot be confused for a version string), so that top-level prerelease packages are not marked invalid.

I'll submit a PR with that fix shortly.

**Comment by isaacs** [comment]
This is not so straightforward.

Since prerelease versions can be frequently broken or incomplete (and that is their intent), even if someone depends on `*`, you could make the argument that this range should not include those versions.  It's not clear that `foo@1.0.0-beta` actually even has the core functionality of the foo package!

From that point of view, prerelease packages actually *don't* satisfy the range (or at least, aren't guaranteed to) and so marking them as invalid is the correct thing to do.

Can you share more about your use case that led you to encounter these errors?  I'd like to understand it better.

**Comment by benjamn** [comment]
I don't disagree with your reasoning, from the perspective of the `semver` package. The `read-installed` package seems to be trying come up with a catch-all version constraint when there is no `package.json` file available, and now there isn't any truly catch-all version constraint. That's probably a good thing, but it's still a problem for `read-installed`.

Here's my use-case:
```sh
mkdir -p temp/node_modules
cd temp
npm install double-ended-queue@2.1.0-0
npm ls
```
Note that `double-ended-queue` is marked invalid because it has a prerelease version, even though that's the version I asked for.

**Comment by benjamn** [comment]
To avoid confusion, I've updated my PR to stop using `*` for unknown package versions: https://github.com/benjamn/read-installed/commit/f8abd793325fad95de891b7f40d8811fc877d0ef

**Comment by iarna** [comment]
It's worth noting, that because [`npm@3`](https://github.com/npm/npm/tree/multi-stage) doesn't use `read-installed` and handles its own logic, it doesn't encounter this bug and so an `npm ls` in this scenario with it does not report the package as invalid. `npm@3` is... imminent... maybe tomorrow?

But we will be maintaining `npm@2` for a while concurrently so I'm not opposed to taking this fix on those grounds.

**Comment by benjamn** [comment]
Oh awesome, I love it when problems disappear because progress is happening elsewhere.
